# Generated by Django 3.1.2 on 2021-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airmusic', '0003_auto_20210605_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='progress',
            field=models.TextField(blank=True, default=''),
        ),
    ]
