# Generated by Django 3.1.2 on 2021-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airmusic', '0005_auto_20210608_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='json',
            field=models.TextField(blank=True, default='This is empty, please add something'),
        ),
        migrations.AlterField(
            model_name='list',
            name='progress',
            field=models.TextField(blank=True, default='Oops! this is empty'),
        ),
    ]
