# Generated by Django 3.1.2 on 2021-06-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airmusic', '0006_auto_20210608_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='code',
            field=models.TextField(blank=True, default='No code here :('),
        ),
    ]
